# Data Loading and Initial Inspection

This notebook is responsible for loading the raw ARI and ILI incidence data used throughout the project.

The data are obtained from the European Centre for Disease Prevention and Control (ECDC) repositories and contain weekly incidence values by country.  
At this stage, the objective is **only to load and inspect the data**, without any preprocessing, imputation, or modeling.

All subsequent notebooks assume that the data have the structure verified here.

In [12]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent   # go up one level
sys.path.insert(0, str(PROJECT_ROOT))

In [3]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.0-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aolas\miniconda3\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\aolas\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ------- -------------------------------- 2.1/11.0 MB 24.2 MB/s eta 0:00:01
   ---------- ----------------------------- 2.9/11.0 MB 7.5 MB/s eta 0:00:02
   ---------------------------------------- 11.0/11.0 MB 20.9 MB/s eta 0:00:00
Downloading numpy-2.4.0-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------  12.1/12.3 MB 76.5 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 48.9 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: pytz, tzdata, numpy, pandas

   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ---------------------------------------- 4/4 [pandas]

Successfully installed numpy-2.4.0 pandas-2.3.3 pytz-2025.2 tzdata-2025.3

## Loading ARI and ILI incidence data

The datasets are stored locally in CSV format and include the following key variables:

- `location`: ISO-2 country code  
- `truth_date`: end date of the epidemiological week (Sunday)  
- `year_week`: epidemiological year and week  
- `value`: incidence per population unit

The dates are converted to proper datetime objects to facilitate time series analysis in later stages.

In [5]:
import pandas as pd
from pathlib import Path

# notebook directory
BASE_DIR = Path.cwd()

# construct paths
DATA_DIR = BASE_DIR.parent / "data"

ari_df = pd.read_csv(DATA_DIR / "latest-ARI_incidence.csv")
ili_df = pd.read_csv(DATA_DIR / "latest-ILI_incidence.csv")

ari_df.head()

  location  truth_date year_week   value
0       BE  2024-10-13  2024-W41  1384.1
1       BE  2024-10-06  2024-W40  1182.0
2       BE  2024-09-29  2024-W39  1216.6
3       BE  2024-09-22  2024-W38   993.0
4       BE  2024-09-15  2024-W37   927.0

In [6]:
ari_df.tail()

     location  truth_date year_week  value
6680       ES  2021-11-07  2021-W44  529.4
6681       ES  2021-10-31  2021-W43  553.8
6682       ES  2021-10-24  2021-W42  535.0
6683       ES  2021-10-17  2021-W41  462.6
6684       ES  2021-10-10  2021-W40  485.0

In [7]:
ari_df.groupby("location").size()

location
BE    524
BG    514
CY     71
CZ    523
DE    524
EE    506
ES    158
FI    380
FR    167
HU     66
LT    508
LU    405
LV    334
MT     30
NL    369
PT    124
RO    513
SI    524
SK    445
dtype: int64

In [8]:
ili_df.head()

  location  truth_date year_week   value
0       AT  2024-10-13  2024-W41  3214.2
1       AT  2024-04-07  2024-W14  1512.6
2       AT  2024-03-31  2024-W13  1629.1
3       AT  2024-03-24  2024-W12  2179.8
4       AT  2024-03-17  2024-W11  1798.0

In [9]:
ili_df.tail()

      location  truth_date year_week  value
10641       ES  2014-11-02  2014-W44    9.5
10642       ES  2014-10-26  2014-W43   11.8
10643       ES  2014-10-19  2014-W42   10.2
10644       ES  2014-10-12  2014-W41   10.1
10645       ES  2014-10-05  2014-W40    7.0

In [10]:
ili_df.groupby("location").size()

location
AT    262
BE    524
CY    242
CZ    523
DK    406
EE    514
ES    199
FI    386
FR    349
GR    514
HR    326
HU    324
IE    523
IS    313
IT    280
LT    510
LU    406
LV    335
MT    364
NL    524
NO    385
PL    520
PT    435
RO    513
SI    524
SK    445
dtype: int64

In [11]:
ari_df = ari_df.sort_values(
    ["location", "truth_date"]
).reset_index(drop=True)

ili_df = ili_df.sort_values(
    ["location", "truth_date"]
).reset_index(drop=True)

In [13]:
ari_df.groupby("location").head(1)

     location  truth_date year_week    value
0          BE  2014-10-05  2014-W40   1407.5
524        BG  2014-10-05  2014-W40    410.4
1038       CY  2014-10-05  2014-W40   5000.0
1109       CZ  2014-10-05  2014-W40    796.5
1632       DE  2014-10-05  2014-W40    946.9
2156       EE  2014-10-05  2014-W40    290.2
2662       ES  2021-10-10  2021-W40    485.0
2820       FI  2015-05-03  2015-W18   6123.8
3200       FR  2020-08-02  2020-W31     20.6
3367       HU  2022-10-09  2022-W40   2130.6
3433       LT  2014-10-05  2014-W40    540.6
3941       LU  2014-10-05  2014-W40  18900.0
4346       LV  2014-10-05  2014-W40   1149.5
4680       MT  2014-10-12  2014-W41      0.0
4710       NL  2015-02-08  2015-W06      0.0
5079       PT  2020-02-16  2020-W07      4.9
5203       RO  2014-10-05  2014-W40    789.7
5716       SI  2014-10-05  2014-W40   1030.7
6240       SK  2014-10-05  2014-W40   1732.1

In [14]:
ari_df.groupby("location").tail(1)

     location  truth_date year_week    value
523        BE  2024-10-13  2024-W41   1384.1
1037       BG  2024-10-13  2024-W41    656.9
1108       CY  2017-10-29  2017-W43   3900.0
1631       CZ  2024-10-13  2024-W41   1086.5
2155       DE  2024-10-13  2024-W41   1913.0
2661       EE  2024-09-29  2024-W39    293.1
2819       ES  2024-10-13  2024-W41    490.6
3199       FI  2024-08-18  2024-W33   2269.2
3366       FR  2024-10-13  2024-W41    261.3
3432       HU  2024-10-13  2024-W41   2191.8
3940       LT  2024-10-13  2024-W41   1137.3
4345       LU  2024-10-13  2024-W41  22400.0
4679       LV  2024-10-13  2024-W41   1557.9
4709       MT  2015-05-17  2015-W20      0.0
5078       NL  2022-10-02  2022-W39    189.4
5202       PT  2023-03-05  2023-W09     61.6
5715       RO  2024-10-13  2024-W41    917.3
6239       SI  2024-10-13  2024-W41   1748.7
6684       SK  2023-04-30  2023-W17   1437.7