In [3]:
# ============================================================
# Starts from:
#   06_combined_tfg_respicast_predictions_long_corrected.csv
#
# Main metrics:
#   - mean_AE
#   - mean_scaled_AE
#   - RMSE
#
# Main table:
#   for each scope / disease / horizon:
#     - top 3 TFG methods
#     - top 2 RespiCast methods excluding baseline
#     - respicast-quantileBaseline
# ============================================================

import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

# ------------------------------------------------------------
# 0) CONFIG
# ------------------------------------------------------------
COMMON6 = ["BE", "CZ", "EE", "LT", "RO", "SI"]

REFERENCE_MODEL = "respicast-quantileBaseline"
REFERENCE_METHOD = f"RespiCast::{REFERENCE_MODEL}"

HORIZONS = [1, 2, 3, 4]

TOP_TFG_N = 3
TOP_RESPICAST_N = 2
MIN_COVERAGE_VS_BASELINE_FOR_MAIN = 0.50

# Incidence is a rate per 100,000, so values above this are impossible.
# They are excluded from the main simplified table and audited separately.
EXTREME_UPPER_BOUND = 100000.0

SCALE_START = pd.Timestamp("2014-01-05")
SCALE_END = pd.Timestamp("2023-12-31")
WEEK_FREQ = "W-SUN"
M_SEASON = 52

# ------------------------------------------------------------
# 1) PATHS
# ------------------------------------------------------------
def find_project_root():
    candidates = [
        Path.cwd(),
        Path.cwd().parent,
        Path.cwd().parent.parent
    ]
    for c in candidates:
        if (c / "results").exists() and (c / "data").exists():
            return c.resolve()
    raise FileNotFoundError("Could not find project root containing 'results' and 'data' folders.")

PROJECT_ROOT = find_project_root()
DATA_DIR = PROJECT_ROOT / "data"
RESULTS_DIR = PROJECT_ROOT / "results"
FINAL_TEST_DIR = RESULTS_DIR / "final_test_2024_2025"

preferred_combined = (
    FINAL_TEST_DIR
    / "respicast_comparison_corrected"
    / "06_combined_tfg_respicast_predictions_long_corrected.csv"
)

if preferred_combined.exists():
    COMBINED_PATH = preferred_combined
else:
    matches = list(RESULTS_DIR.rglob("06_combined_tfg_respicast_predictions_long_corrected.csv"))
    if not matches:
        raise FileNotFoundError(
            "Could not find 06_combined_tfg_respicast_predictions_long_corrected.csv. "
            "Run the corrected RespiCast comparison notebook first."
        )
    COMBINED_PATH = matches[0]

OUT_DIR = FINAL_TEST_DIR / "respicast_final_clean_tables"
OUT_DIR.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("DATA_DIR:", DATA_DIR)
print("RESULTS_DIR:", RESULTS_DIR)
print("COMBINED_PATH:", COMBINED_PATH)
print("OUT_DIR:", OUT_DIR)

# ------------------------------------------------------------
# 2) IMPORT SRC FUNCTIONS FOR SCALE COMPUTATION
# ------------------------------------------------------------
sys.path.insert(0, str(PROJECT_ROOT))

try:
    from src.impute import impute_series_weekly
    from src.metrics import mase_scale_seasonal
    SRC_OK = True
    print("src functions loaded.")
except Exception as e:
    SRC_OK = False
    print("WARNING: src functions not available. Fallback scale computation will be used.")
    print("Error:", e)

# ------------------------------------------------------------
# 3) HELPERS
# ------------------------------------------------------------
def normalize_columns(df):
    out = df.copy()
    out.columns = [str(c).strip() for c in out.columns]
    return out

def find_incidence_file(disease):
    """
    Robustly find latest ARI/ILI incidence files, regardless of case.
    """
    disease = disease.upper()
    candidates = [
        DATA_DIR / f"latest-{disease}_incidence.csv",
        DATA_DIR / f"latest-{disease.lower()}_incidence.csv",
        DATA_DIR / f"latest_{disease}_incidence.csv",
        DATA_DIR / f"latest_{disease.lower()}_incidence.csv",
    ]

    for p in candidates:
        if p.exists():
            return p

    all_csv = list(DATA_DIR.glob("*.csv"))
    matches = [
        p for p in all_csv
        if "latest" in p.name.lower()
        and disease.lower() in p.name.lower()
        and "incidence" in p.name.lower()
    ]

    if matches:
        return sorted(matches)[-1]

    matches = [
        p for p in all_csv
        if disease.lower() in p.name.lower()
        and "incidence" in p.name.lower()
    ]

    if matches:
        return sorted(matches)[-1]

    raise FileNotFoundError(f"No incidence file found for {disease} in {DATA_DIR}")

def read_incidence_file(disease):
    p = find_incidence_file(disease)
    df = pd.read_csv(p)
    df = normalize_columns(df)

    required = {"truth_date", "location", "value"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Incidence file {p} is missing columns: {missing}")

    df["truth_date"] = pd.to_datetime(df["truth_date"], errors="coerce")
    df["location"] = df["location"].astype(str)
    df["value"] = pd.to_numeric(df["value"], errors="coerce")

    df = (
        df.dropna(subset=["truth_date", "location", "value"])
        .drop_duplicates(["location", "truth_date"], keep="last")
        .sort_values(["location", "truth_date"])
        .reset_index(drop=True)
    )

    print(f"{disease} incidence file:", p.name, "| shape:", df.shape)
    return df

def compute_scale_for_location(df_hist, location):
    """
    Seasonal MASE scale computed on pre-final-test historical data.
    Same idea as the rest of the TFG:
    mean absolute seasonal difference with m=52.
    """
    calendar = pd.date_range(SCALE_START, SCALE_END, freq=WEEK_FREQ)

    dfloc = df_hist[df_hist["location"] == location][["truth_date", "value"]].copy()
    dfloc["truth_date"] = pd.to_datetime(dfloc["truth_date"], errors="coerce")
    dfloc["value"] = pd.to_numeric(dfloc["value"], errors="coerce")
    dfloc = dfloc.dropna(subset=["truth_date", "value"])

    if dfloc.empty:
        return np.nan

    if SRC_OK:
        s = impute_series_weekly(
            dfloc,
            calendar=calendar,
            trim_to_first_obs=True,
            max_gap_knn=8
        )
        scale = float(mase_scale_seasonal(s, m=M_SEASON))
    else:
        s = (
            dfloc.sort_values("truth_date")
            .drop_duplicates("truth_date", keep="last")
            .set_index("truth_date")["value"]
            .reindex(calendar)
            .astype(float)
        )
        s = s.interpolate(limit_direction="both").ffill().bfill()
        scale = float((s - s.shift(M_SEASON)).abs().dropna().mean())

    if not np.isfinite(scale) or scale <= 0:
        return np.nan

    return scale

def build_scales_for_eval(df_eval):
    ari_hist = read_incidence_file("ARI")
    ili_hist = read_incidence_file("ILI")

    rows = []

    for disease, hist in [("ARI", ari_hist), ("ILI", ili_hist)]:
        locs = sorted(df_eval[df_eval["disease"] == disease]["location"].unique())

        for loc in locs:
            try:
                scale = compute_scale_for_location(hist, loc)
            except Exception as e:
                print(f"WARNING: failed scale for {disease}-{loc}: {e}")
                scale = np.nan

            rows.append({
                "disease": disease,
                "location": loc,
                "mase_scale": scale
            })

    scales = pd.DataFrame(rows)

    if scales.empty:
        raise RuntimeError("Scale table is empty. Cannot compute scaled_AE.")

    if scales["mase_scale"].isna().any():
        bad = scales[scales["mase_scale"].isna()].copy()
        print("\nWARNING: missing mase_scale for these disease-location pairs:")
        display(bad)

    return scales

def add_scope(df, scope_name):
    out = df.copy()
    out["scope"] = scope_name
    return out

def safe_ratio(num, den):
    if pd.isna(num) or pd.isna(den) or den == 0:
        return np.nan
    return num / den

# ------------------------------------------------------------
# 4) LOAD COMBINED CORRECTED PREDICTIONS
# ------------------------------------------------------------
df = pd.read_csv(COMBINED_PATH)
df = normalize_columns(df)

required = {"origin", "target", "disease", "location", "h", "y", "pred", "model", "source"}
missing = required - set(df.columns)
if missing:
    raise ValueError(f"Missing required columns in combined corrected file: {missing}")

if "method" not in df.columns:
    df["method"] = df["source"].astype(str) + "::" + df["model"].astype(str)

df["origin"] = pd.to_datetime(df["origin"], errors="coerce")
df["target"] = pd.to_datetime(df["target"], errors="coerce")
df["disease"] = df["disease"].astype(str).str.upper()
df["location"] = df["location"].astype(str)
df["h"] = pd.to_numeric(df["h"], errors="coerce")
df["y"] = pd.to_numeric(df["y"], errors="coerce")
df["pred"] = pd.to_numeric(df["pred"], errors="coerce")
df["model"] = df["model"].astype(str)
df["source"] = df["source"].astype(str)
df["method"] = df["method"].astype(str)

original_rows = len(df)

df = df.dropna(
    subset=["origin", "target", "disease", "location", "h", "y", "model", "source", "method"]
).copy()

df = df[np.isfinite(df["y"])].copy()

# Date-based horizon is the final horizon definition.
df["h_from_dates"] = ((df["target"] - df["origin"]).dt.days / 7).round(6)

horizon_date_audit = (
    df.groupby(["source", "model", "h", "h_from_dates"], as_index=False)
    .size()
    .rename(columns={"size": "n_rows"})
    .sort_values(["source", "model", "h", "h_from_dates"])
)

df = df[df["h_from_dates"].isin(HORIZONS)].copy()
df["h_original_column"] = df["h"]
df["h"] = df["h_from_dates"].astype(int)
df = df[df["h"].isin(HORIZONS)].copy()

print("\nOriginal rows:", original_rows)
print("Rows after key/truth/date-horizon cleaning:", len(df))
print("\nHorizon/date audit preview:")
display(horizon_date_audit.head(50))

# ------------------------------------------------------------
# 5) PREDICTION QUALITY AUDITS
# ------------------------------------------------------------
df["pred_is_finite"] = np.isfinite(df["pred"])
df["pred_is_negative"] = df["pred_is_finite"] & (df["pred"] < 0)
df["pred_is_extreme_high"] = df["pred_is_finite"] & (df["pred"] > EXTREME_UPPER_BOUND)

df["pred_quality_flag"] = np.select(
    [
        ~df["pred_is_finite"],
        df["pred_is_negative"],
        df["pred_is_extreme_high"]
    ],
    [
        "non_finite_prediction",
        "negative_prediction",
        "above_100000_per_100000"
    ],
    default="finite_non_negative_plausible"
)

prediction_quality_audit = (
    df.groupby(["source", "model", "method", "disease", "h", "pred_quality_flag"], as_index=False)
    .agg(
        n_rows=("pred", "size"),
        min_pred=("pred", "min"),
        max_pred=("pred", "max"),
        mean_pred=("pred", "mean"),
        first_origin=("origin", "min"),
        last_origin=("origin", "max"),
        first_target=("target", "min"),
        last_target=("target", "max")
    )
    .sort_values(["pred_quality_flag", "source", "model", "disease", "h"])
)

invalid_or_extreme_rows = df[df["pred_quality_flag"] != "finite_non_negative_plausible"].copy()

print("\nPrediction quality audit:")
display(prediction_quality_audit)

print("\nInvalid/extreme rows:", invalid_or_extreme_rows.shape)
if len(invalid_or_extreme_rows) > 0:
    display(invalid_or_extreme_rows.head(20))

# Main evaluation:
# - non-finite predictions cannot be evaluated
# - extremely high impossible predictions are excluded from main comparison and audited
# - negative finite predictions are kept and penalised by their error
df_eval = df[df["pred_is_finite"] & (~df["pred_is_extreme_high"])].copy()

# ------------------------------------------------------------
# 6) DEDUPLICATE EXACT FORECAST KEYS IF NECESSARY
# ------------------------------------------------------------
PRED_KEYS = ["source", "model", "method", "disease", "location", "origin", "target", "h"]

duplicate_rows = df_eval[df_eval.duplicated(PRED_KEYS, keep=False)].copy()

if len(duplicate_rows) > 0:
    print("\nWARNING: duplicated prediction keys found. Aggregating predictions by mean.")
    display(duplicate_rows.head(20))

    duplicate_audit = (
        duplicate_rows.groupby(PRED_KEYS, as_index=False)
        .agg(
            n_duplicates=("pred", "size"),
            min_pred=("pred", "min"),
            max_pred=("pred", "max"),
            mean_pred=("pred", "mean"),
            y_min=("y", "min"),
            y_max=("y", "max")
        )
    )
else:
    duplicate_audit = pd.DataFrame(columns=PRED_KEYS + ["n_duplicates", "min_pred", "max_pred", "mean_pred", "y_min", "y_max"])

# Aggregate only if duplicates exist. y should be identical for duplicate forecast keys.
df_eval = (
    df_eval.groupby(PRED_KEYS, as_index=False)
    .agg(
        y=("y", "mean"),
        pred=("pred", "mean"),
        pred_is_negative=("pred_is_negative", "max"),
        pred_is_extreme_high=("pred_is_extreme_high", "max"),
        pred_quality_flag=("pred_quality_flag", lambda s: "|".join(sorted(set(map(str, s)))))
    )
)

# ------------------------------------------------------------
# 7) ADD SCOPES
# ------------------------------------------------------------
scoped = pd.concat(
    [
        add_scope(df_eval, "global"),
        add_scope(df_eval[df_eval["location"].isin(COMMON6)], "common6")
    ],
    ignore_index=True
)

# ------------------------------------------------------------
# 8) ADD MASE SCALES ROBUSTLY
# ------------------------------------------------------------
scales = build_scales_for_eval(scoped)

scale_like_cols = [c for c in scoped.columns if c.lower().startswith("mase_scale")]
if scale_like_cols:
    print("Dropping existing scale-like columns before merge:", scale_like_cols)
    scoped = scoped.drop(columns=scale_like_cols)

scoped = scoped.merge(
    scales,
    on=["disease", "location"],
    how="left",
    validate="many_to_one"
)

if "mase_scale" not in scoped.columns:
    raise RuntimeError(
        "mase_scale was not created after merge. Columns are: "
        + ", ".join(scoped.columns)
    )

if scoped["mase_scale"].isna().any():
    bad_scale_rows = scoped[scoped["mase_scale"].isna()][["disease", "location"]].drop_duplicates()
    print("\nERROR: missing mase_scale for these pairs:")
    display(bad_scale_rows)
    raise RuntimeError("Missing mase_scale values. Fix scales before evaluation.")

scoped["AE"] = (scoped["y"] - scoped["pred"]).abs()
scoped["SE"] = (scoped["y"] - scoped["pred"]) ** 2
scoped["scaled_AE"] = scoped["AE"] / scoped["mase_scale"]

# ------------------------------------------------------------
# 9) PAIR EACH METHOD WITH RESPICAST BASELINE
# ------------------------------------------------------------
ref = scoped[scoped["method"] == REFERENCE_METHOD].copy()

if ref.empty:
    raise ValueError(
        f"No reference rows found for {REFERENCE_METHOD}. "
        "Check that respicast-quantileBaseline exists in the combined corrected file."
    )

PAIR_KEYS = ["scope", "disease", "location", "origin", "target", "h"]

ref_dup = ref.duplicated(PAIR_KEYS).sum()
if ref_dup > 0:
    print(f"\nWARNING: baseline has {ref_dup} duplicated keys after cleaning. Aggregating by mean.")
    ref = (
        ref.groupby(PAIR_KEYS, as_index=False)
        .agg(
            y=("y", "mean"),
            pred=("pred", "mean"),
            AE=("AE", "mean"),
            SE=("SE", "mean"),
            scaled_AE=("scaled_AE", "mean")
        )
    )

ref_for_pairing = ref[
    PAIR_KEYS + ["y", "pred", "AE", "SE", "scaled_AE"]
].rename(
    columns={
        "y": "y_ref",
        "pred": "pred_ref",
        "AE": "AE_ref",
        "SE": "SE_ref",
        "scaled_AE": "scaled_AE_ref"
    }
)

cand_for_pairing = scoped[
    PAIR_KEYS + [
        "source", "model", "method", "y", "pred",
        "AE", "SE", "scaled_AE",
        "pred_is_negative", "pred_quality_flag"
    ]
].rename(
    columns={
        "y": "y_model",
        "pred": "pred_model",
        "AE": "AE_model",
        "SE": "SE_model",
        "scaled_AE": "scaled_AE_model"
    }
)

paired = cand_for_pairing.merge(ref_for_pairing, on=PAIR_KEYS, how="inner")

paired["truth_abs_diff_vs_ref"] = (paired["y_model"] - paired["y_ref"]).abs()
max_truth_diff = paired["truth_abs_diff_vs_ref"].max()

print("\nPaired rows:", len(paired))
print("Max truth difference after pairing:", max_truth_diff)

if max_truth_diff > 1e-8:
    raise ValueError("Truth mismatch after pairing with baseline. Evaluation is not safe.")

# ------------------------------------------------------------
# 10) ZERO ERROR AUDIT
# ------------------------------------------------------------
paired["model_AE_zero"] = np.isclose(paired["AE_model"], 0.0)
paired["ref_AE_zero"] = np.isclose(paired["AE_ref"], 0.0)
paired["both_AE_zero"] = paired["model_AE_zero"] & paired["ref_AE_zero"]
paired["y_zero"] = np.isclose(paired["y_model"], 0.0)
paired["pred_model_zero"] = np.isclose(paired["pred_model"], 0.0)
paired["pred_ref_zero"] = np.isclose(paired["pred_ref"], 0.0)

zero_error_audit = (
    paired.groupby(["scope", "source", "model", "method", "disease", "h"], as_index=False)
    .agg(
        n_pairs=("AE_model", "size"),
        n_y_zero=("y_zero", "sum"),
        n_pred_model_zero=("pred_model_zero", "sum"),
        n_pred_ref_zero=("pred_ref_zero", "sum"),
        n_model_AE_zero=("model_AE_zero", "sum"),
        n_ref_AE_zero=("ref_AE_zero", "sum"),
        n_both_AE_zero=("both_AE_zero", "sum"),
        mean_AE_model=("AE_model", "mean"),
        mean_AE_ref=("AE_ref", "mean")
    )
    .sort_values(["scope", "disease", "h", "source", "model"])
)

# ------------------------------------------------------------
# 11) METRIC SUMMARY
# ------------------------------------------------------------
reference_universe = (
    paired[paired["method"] == REFERENCE_METHOD]
    .groupby(["scope", "disease", "h"], as_index=False)
    .agg(
        reference_pairs=("AE_model", "size"),
        reference_countries=("location", "nunique"),
        reference_first_origin=("origin", "min"),
        reference_last_origin=("origin", "max"),
        reference_first_target=("target", "min"),
        reference_last_target=("target", "max")
    )
)

metric_summary = (
    paired.groupby(["scope", "source", "model", "method", "disease", "h"], as_index=False)
    .agg(
        mean_AE=("AE_model", "mean"),
        median_AE=("AE_model", "median"),
        RMSE=("SE_model", lambda x: float(np.sqrt(np.mean(x)))),
        mean_scaled_AE=("scaled_AE_model", "mean"),
        median_scaled_AE=("scaled_AE_model", "median"),
        mean_AE_ref_baseline=("AE_ref", "mean"),
        mean_scaled_AE_ref_baseline=("scaled_AE_ref", "mean"),
        n_pairs=("AE_model", "size"),
        n_countries=("location", "nunique"),
        first_origin=("origin", "min"),
        last_origin=("origin", "max"),
        first_target=("target", "min"),
        last_target=("target", "max"),
        n_negative_predictions=("pred_is_negative", "sum")
    )
)

metric_summary = metric_summary.merge(
    reference_universe,
    on=["scope", "disease", "h"],
    how="left",
    validate="many_to_one"
)

metric_summary["coverage_vs_baseline"] = metric_summary["n_pairs"] / metric_summary["reference_pairs"]

metric_summary["MAE_ratio_vs_baseline"] = metric_summary.apply(
    lambda r: safe_ratio(r["mean_AE"], r["mean_AE_ref_baseline"]),
    axis=1
)

metric_summary["scaled_AE_ratio_vs_baseline"] = metric_summary.apply(
    lambda r: safe_ratio(r["mean_scaled_AE"], r["mean_scaled_AE_ref_baseline"]),
    axis=1
)

metric_summary["rank_by_scaled_AE"] = (
    metric_summary.groupby(["scope", "disease", "h"])["mean_scaled_AE"]
    .rank(method="min", ascending=True)
    .astype(int)
)

metric_summary["rank_by_AE"] = (
    metric_summary.groupby(["scope", "disease", "h"])["mean_AE"]
    .rank(method="min", ascending=True)
    .astype(int)
)

metric_summary = metric_summary.sort_values(
    ["scope", "disease", "h", "mean_scaled_AE", "mean_AE"]
).reset_index(drop=True)

print("\nMetric summary preview:")
display(metric_summary.head(50))

# ------------------------------------------------------------
# 12) MAIN SIMPLIFIED TABLE
# ------------------------------------------------------------
main_parts = []

for (scope, disease, h), sub in metric_summary.groupby(["scope", "disease", "h"]):
    sub = sub.copy()

    tfg_top = (
        sub[sub["source"] == "TFG"]
        .sort_values(["mean_scaled_AE", "mean_AE"])
        .head(TOP_TFG_N)
    )

    respicast_top = (
        sub[
            (sub["source"] == "RespiCast")
            & (sub["method"] != REFERENCE_METHOD)
            & (sub["coverage_vs_baseline"] >= MIN_COVERAGE_VS_BASELINE_FOR_MAIN)
        ]
        .sort_values(["mean_scaled_AE", "mean_AE"])
        .head(TOP_RESPICAST_N)
    )

    baseline = sub[sub["method"] == REFERENCE_METHOD]

    selected = pd.concat([tfg_top, respicast_top, baseline], ignore_index=True)
    selected = selected.drop_duplicates(subset=["scope", "disease", "h", "method"])
    selected = selected.sort_values(["mean_scaled_AE", "mean_AE"]).reset_index(drop=True)
    selected["main_table_rank"] = np.arange(1, len(selected) + 1)

    main_parts.append(selected)

main_table = pd.concat(main_parts, ignore_index=True)

main_cols = [
    "scope",
    "disease",
    "h",
    "main_table_rank",
    "source",
    "model",
    "mean_AE",
    "mean_scaled_AE",
    "RMSE",
    "median_AE",
    "n_pairs",
    "reference_pairs",
    "coverage_vs_baseline",
    "n_countries",
    "mean_AE_ref_baseline",
    "MAE_ratio_vs_baseline",
    "scaled_AE_ratio_vs_baseline",
    "n_negative_predictions",
    "first_origin",
    "last_origin",
    "first_target",
    "last_target"
]

main_table = main_table[main_cols].copy()

print("\nMAIN TABLE:")
display(main_table)

# ------------------------------------------------------------
# 13) AUXILIARY TABLES
# ------------------------------------------------------------
top10_all = (
    metric_summary.sort_values(["scope", "disease", "h", "mean_scaled_AE", "mean_AE"])
    .groupby(["scope", "disease", "h"], group_keys=False)
    .head(10)
    .reset_index(drop=True)
)

top10_coverage_filtered = (
    metric_summary[
        (metric_summary["source"] == "TFG")
        | (metric_summary["coverage_vs_baseline"] >= MIN_COVERAGE_VS_BASELINE_FOR_MAIN)
    ]
    .sort_values(["scope", "disease", "h", "mean_scaled_AE", "mean_AE"])
    .groupby(["scope", "disease", "h"], group_keys=False)
    .head(10)
    .reset_index(drop=True)
)

tfg_positions = (
    metric_summary[metric_summary["source"] == "TFG"]
    .sort_values(["scope", "disease", "h", "mean_scaled_AE", "mean_AE"])
    .reset_index(drop=True)
)

respicast_positions = (
    metric_summary[metric_summary["source"] == "RespiCast"]
    .sort_values(["scope", "disease", "h", "mean_scaled_AE", "mean_AE"])
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# 14) COLUMN DICTIONARY
# ------------------------------------------------------------
column_dictionary = pd.DataFrame([
    {
        "column": "scope",
        "definition": "Evaluation universe. global = all countries available for the TFG final evaluation for each disease; common6 = BE, CZ, EE, LT, RO and SI."
    },
    {
        "column": "disease",
        "definition": "Respiratory indicator: ARI or ILI."
    },
    {
        "column": "h",
        "definition": "Forecast horizon in weeks. h=1 means target = origin + 1 week."
    },
    {
        "column": "main_table_rank",
        "definition": "Rank inside each scope-disease-horizon block in the simplified table. Lower is better."
    },
    {
        "column": "source",
        "definition": "Origin of the method: TFG or RespiCast."
    },
    {
        "column": "model",
        "definition": "Model name as stored in the prediction files."
    },
    {
        "column": "mean_AE",
        "definition": "Mean absolute error of the model on the matched forecast-observation pairs."
    },
    {
        "column": "mean_scaled_AE",
        "definition": "Mean absolute error divided by the seasonal naive in-sample scale for the corresponding disease and country."
    },
    {
        "column": "RMSE",
        "definition": "Root mean squared error on the matched forecast-observation pairs."
    },
    {
        "column": "median_AE",
        "definition": "Median absolute error on the matched forecast-observation pairs."
    },
    {
        "column": "n_pairs",
        "definition": "Number of matched forecast-observation pairs used for that method."
    },
    {
        "column": "reference_pairs",
        "definition": "Number of available respicast-quantileBaseline pairs for the same scope, disease and horizon."
    },
    {
        "column": "coverage_vs_baseline",
        "definition": "n_pairs divided by reference_pairs. It measures the method's overlap with the RespiCast baseline."
    },
    {
        "column": "n_countries",
        "definition": "Number of countries represented in the matched comparison."
    },
    {
        "column": "mean_AE_ref_baseline",
        "definition": "Mean AE of respicast-quantileBaseline on exactly the same matched pairs as the evaluated method."
    },
    {
        "column": "MAE_ratio_vs_baseline",
        "definition": "mean_AE / mean_AE_ref_baseline. Values below 1 mean the method has lower MAE than the baseline on the same matched pairs."
    },
    {
        "column": "scaled_AE_ratio_vs_baseline",
        "definition": "mean_scaled_AE / mean_scaled_AE_ref_baseline. Values below 1 mean the method has lower scaled AE than the baseline on the same matched pairs."
    },
    {
        "column": "n_negative_predictions",
        "definition": "Number of negative finite predictions. They are kept in the evaluation and penalised through their error, but audited because incidence cannot be negative."
    }
])

# ------------------------------------------------------------
# 15) METHODOLOGY NOTES
# ------------------------------------------------------------
methodology_notes = f"""
Final RespiCast comparison methodology
======================================

Input
-----
This notebook starts from:
{COMBINED_PATH}

Forecast alignment
------------------
The evaluation keeps only rows where:
target = origin + h weeks, with h in {{1, 2, 3, 4}}.

The final horizon used in the tables is computed from the dates, not only from
the raw horizon column.

Reference model
---------------
The RespiCast reference model is:
{REFERENCE_METHOD}

Pairing
-------
Each method is compared only on forecast-observation pairs that are also
available for respicast-quantileBaseline. The matching keys are:
scope, disease, location, origin, target and h.

Main metrics
------------
The main comparison uses:
- mean_AE
- mean_scaled_AE
- RMSE

The primary ranking in the simplified table is by mean_scaled_AE and then mean_AE.

Why log2 is not used as the main metric
---------------------------------------
Pointwise log2(AE_ref / AE_model) is problematic when individual absolute errors
are zero. Zero errors can occur legitimately when incidence is very low or zero.

The aggregate log2(mean_AE_ref / mean_AE_model) is also not used as the main
criterion because it gives the same ordering as mean_AE on the same paired sample.

Therefore, the final tables use direct MAE and scaled AE metrics.

Zero errors
-----------
Zero absolute errors are valid. They are not removed. They are included in MAE
and scaled AE. They are reported separately in the zero-error audit.

Prediction quality
------------------
Non-finite predictions mean NaN, +inf or -inf. These cannot be evaluated and are
excluded.
Extremely high forecasts above {EXTREME_UPPER_BOUND:,.0f} per 100,000 are excluded
from the main comparison and reported in the quality audit.
Negative finite forecasts are kept in the evaluation and penalised by their error,
but they are audited separately because incidence cannot be negative.

Simplified main table
---------------------
For each scope, disease and horizon, the simplified main table contains:
- the top {TOP_TFG_N} TFG methods,
- the top {TOP_RESPICAST_N} RespiCast methods excluding the baseline,
- respicast-quantileBaseline.

For RespiCast competitors, the table only includes methods with
coverage_vs_baseline >= {MIN_COVERAGE_VS_BASELINE_FOR_MAIN}.
"""

# ------------------------------------------------------------
# 16) SAVE OUTPUTS
# ------------------------------------------------------------
outputs = {
    "00_column_dictionary.csv": column_dictionary,
    "01_horizon_date_audit.csv": horizon_date_audit,
    "02_prediction_quality_audit.csv": prediction_quality_audit,
    "03_invalid_or_extreme_prediction_rows.csv": invalid_or_extreme_rows,
    "04_duplicate_prediction_key_audit.csv": duplicate_audit,
    "05_scales_used.csv": scales,
    "06_paired_forecasts_vs_baseline.csv": paired,
    "07_zero_error_audit.csv": zero_error_audit,
    "08_metric_summary_all_methods.csv": metric_summary,
    "09_MAIN_top3_TFG_vs_top2_RespiCast_plus_baseline.csv": main_table,
    "10_top10_all_methods_by_scope_disease_horizon.csv": top10_all,
    "11_top10_coverage_filtered.csv": top10_coverage_filtered,
    "12_tfg_positions_only.csv": tfg_positions,
    "13_respicast_positions_only.csv": respicast_positions,
    "14_reference_universe.csv": reference_universe
}

for fname, table in outputs.items():
    table.to_csv(OUT_DIR / fname, index=False)

with open(OUT_DIR / "00_methodology_notes.txt", "w", encoding="utf-8") as f:
    f.write(methodology_notes)

print("\nSaved final clean RespiCast comparison outputs to:")
print(OUT_DIR)

print("\nGenerated files:")
for fname in outputs:
    print("-", fname)
print("- 00_methodology_notes.txt")

print("\n============================================================")
print("MAIN FINAL TABLE")
print("============================================================")
display(main_table)

print("\n============================================================")
print("TFG POSITIONS")
print("============================================================")
display(tfg_positions)

print("\n============================================================")
print("ZERO ERROR AUDIT")
print("============================================================")
display(zero_error_audit)

print("\n============================================================")
print("PREDICTION QUALITY AUDIT")
print("============================================================")
display(prediction_quality_audit)

print("\n============================================================")
print("SCALES USED")
print("============================================================")
display(scales)

PROJECT_ROOT: C:\Users\aolas\UNI PYTHON\TFG
DATA_DIR: C:\Users\aolas\UNI PYTHON\TFG\data
RESULTS_DIR: C:\Users\aolas\UNI PYTHON\TFG\results
COMBINED_PATH: C:\Users\aolas\UNI PYTHON\TFG\results\final_test_2024_2025\respicast_comparison_corrected\06_combined_tfg_respicast_predictions_long_corrected.csv
OUT_DIR: C:\Users\aolas\UNI PYTHON\TFG\results\final_test_2024_2025\respicast_final_clean_tables
src functions loaded.

Original rows: 92961
Rows after key/truth/date-horizon cleaning: 92961

Horizon/date audit preview:

       source                  model  h  h_from_dates  n_rows
0   RespiCast            ECDC-SARIMA  1           1.0     927
1   RespiCast            ECDC-SARIMA  2           2.0     907
2   RespiCast            ECDC-SARIMA  3           3.0     894
3   RespiCast            ECDC-SARIMA  4           4.0     878
4   RespiCast      ECDC-soca_simplex  1           1.0    1021
5   RespiCast      ECDC-soca_simplex  2           2.0     996
6   RespiCast      ECDC-soca_simplex  3           3.0     967
7   RespiCast      ECDC-soca_simplex  4           4.0     940
8   RespiCast        ISI-FluABCaster  1           1.0     464
9   RespiCast        ISI-FluABCaster  2           2.0     444
10  RespiCast        ISI-FluABCaster  3           3.0     426
11  RespiCast        ISI-FluABCaster  4           4.0     408
12  RespiCast           ISI-FluBcast  1           1.0     757
13  RespiCast           ISI-FluBcast  2           2.0     744
14  RespiCast           ISI-FluBcast  3           3.0     729
15  RespiCast           ISI-FluBcast  4           4.0     714
16  RespiCast              ISI-GLEAM  1           1.0     357
17  RespiCast              ISI-GLEAM  2           2.0     344
18  RespiCast              ISI-GLEAM  3           3.0     331
19  RespiCast              ISI-GLEAM  4           4.0     318
20  RespiCast             ISI-LSTFlu  1           1.0     371
21  RespiCast             ISI-LSTFlu  2           2.0     349
22  RespiCast             ISI-LSTFlu  3           3.0     336
23  RespiCast             ISI-LSTFlu  4           4.0     336
24  RespiCast       ISI-RC_AdaptEns2  1           1.0     207
25  RespiCast       ISI-RC_AdaptEns2  2           2.0     207
26  RespiCast       ISI-RC_AdaptEns2  3           3.0     198
27  RespiCast       ISI-RC_AdaptEns2  4           4.0     190
28  RespiCast           ISI-SEIR_BRW  1           1.0     221
29  RespiCast           ISI-SEIR_BRW  2           2.0     221
30  RespiCast           ISI-SEIR_BRW  3           3.0     221
31  RespiCast           ISI-SEIR_BRW  4           4.0     220
32  RespiCast     ItaLuxColab-EpiEKF  1           1.0     537
33  RespiCast     ItaLuxColab-EpiEKF  2           2.0     527
34  RespiCast     ItaLuxColab-EpiEKF  3           3.0     518
35  RespiCast     ItaLuxColab-EpiEKF  4           4.0     508
36  RespiCast  ItaLuxColab-EpiNetEKF  1           1.0     537
37  RespiCast  ItaLuxColab-EpiNetEKF  2           2.0     527
38  RespiCast  ItaLuxColab-EpiNetEKF  3           3.0     518
39  RespiCast  ItaLuxColab-EpiNetEKF  4           4.0     508
40  RespiCast      MRC_GIDA-CATBoost  1           1.0      15
41  RespiCast      MRC_GIDA-CATBoost  2           2.0      15
42  RespiCast      MRC_GIDA-CATBoost  3           3.0      15
43  RespiCast      MRC_GIDA-CATBoost  4           4.0      15
44  RespiCast        MRC_GIDA-NBEATS  1           1.0     143
45  RespiCast        MRC_GIDA-NBEATS  2           2.0     133
46  RespiCast        MRC_GIDA-NBEATS  3           3.0     124
47  RespiCast        MRC_GIDA-NBEATS  4           4.0     112
48  RespiCast         MRC_GIDA-NHiTS  1           1.0     143
49  RespiCast         MRC_GIDA-NHiTS  2           2.0     133

Prediction quality audit:

,source,model,method,disease,h,pred_quality_flag,n_rows,min_pred,max_pred,mean_pred,first_origin,last_origin,first_target,last_target
112,RespiCast,NotreDame-Rt_cocirc,RespiCast::NotreDame-Rt_cocirc,ILI,1,above_100000_per_100000,1,2.842952e+08,2.842952e+08,2.842952e+08,2025-06-15,2025-06-15,2025-06-22,2025-06-22
114,RespiCast,NotreDame-Rt_cocirc,RespiCast::NotreDame-Rt_cocirc,ILI,2,above_100000_per_100000,1,5.725977e+15,5.725977e+15,5.725977e+15,2025-06-15,2025-06-15,2025-06-29,2025-06-29
116,RespiCast,NotreDame-Rt_cocirc,RespiCast::NotreDame-Rt_cocirc,ILI,3,above_100000_per_100000,1,1.153267e+23,1.153267e+23,1.153267e+23,2025-06-15,2025-06-15,2025-07-06,2025-07-06
118,RespiCast,NotreDame-Rt_cocirc,RespiCast::NotreDame-Rt_cocirc,ILI,4,above_100000_per_100000,1,2.322790e+30,2.322790e+30,2.322790e+30,2025-06-15,2025-06-15,2025-07-13,2025-07-13
0,RespiCast,ECDC-SARIMA,RespiCast::ECDC-SARIMA,ARI,1,finite_non_negative_plausible,407,9.150812e+00,2.828806e+03,8.908229e+02,2024-10-13,2025-12-07,2024-10-20,2025-12-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,TFG,autoARIMA,TFG::autoARIMA,ILI,2,negative_prediction,33,-1.580170e+01,-2.948716e-98,-2.809473e+00,2024-03-10,2025-11-09,2024-03-24,2025-11-23
219,TFG,autoARIMA,TFG::autoARIMA,ILI,3,negative_prediction,46,-2.740079e+01,-2.603163e-98,-3.916548e+00,2024-03-10,2025-11-09,2024-03-31,2025-11-30
221,TFG,autoARIMA,TFG::autoARIMA,ILI,4,negative_prediction,56,-2.709863e+01,-1.961124e-98,-4.294071e+00,2024-01-07,2025-11-09,2024-02-04,2025-12-07
227,TFG,ensemble_mean_5,TFG::ensemble_mean_5,ILI,1,negative_prediction,1,-2.853516e-01,-2.853516e-01,-2.853516e-01,2025-05-11,2025-05-11,2025-05-18,2025-05-18
229,TFG,ensemble_mean_5,TFG::ensemble_mean_5,ILI,2,negative_prediction,1,-1.957035e-01,-1.957035e-01,-1.957035e-01,2025-05-11,2025-05-11,2025-05-25,2025-05-25

Invalid/extreme rows: (352, 27)

,origin,target,disease,location,h,y,pred,model,source,method,...,error,abs_error,squared_error,scaled_abs_error,h_from_dates,h_original_column,pred_is_finite,pred_is_negative,pred_is_extreme_high,pred_quality_flag
3742,2025-03-30,2025-04-06,ARI,EE,1,210.0,-1.282911,autoARIMA,TFG,TFG::autoARIMA,...,211.282911,211.282911,44640.468638,2.644349,1.0,1,True,True,False,negative_prediction
3745,2025-03-30,2025-04-27,ARI,EE,4,182.4,-5.536772,autoARIMA,TFG,TFG::autoARIMA,...,187.936772,187.936772,35320.230308,2.352157,4.0,4,True,True,False,negative_prediction
6657,2024-02-18,2024-03-17,ILI,BE,4,155.0,-2.950781,autoARIMA,TFG,TFG::autoARIMA,...,157.950781,157.950781,24948.449178,1.504732,4.0,4,True,True,False,negative_prediction
6669,2024-03-10,2024-04-07,ILI,BE,4,95.7,-1.617184,autoARIMA,TFG,TFG::autoARIMA,...,97.317184,97.317184,9470.634330,0.927101,4.0,4,True,True,False,negative_prediction
6675,2024-03-24,2024-04-07,ILI,BE,2,95.7,-14.254379,autoARIMA,TFG,TFG::autoARIMA,...,109.954379,109.954379,12089.965402,1.047490,2.0,2,True,True,False,negative_prediction
6676,2024-03-24,2024-04-14,ILI,BE,3,43.3,-27.400786,autoARIMA,TFG,TFG::autoARIMA,...,70.700786,70.700786,4998.601190,0.673537,3.0,3,True,True,False,negative_prediction
6677,2024-03-24,2024-04-21,ILI,BE,4,54.5,-18.749947,autoARIMA,TFG,TFG::autoARIMA,...,73.249947,73.249947,5365.554772,0.697822,4.0,4,True,True,False,negative_prediction
6704,2024-05-12,2024-06-02,ILI,BE,3,21.7,-0.061143,autoARIMA,TFG,TFG::autoARIMA,...,21.761143,21.761143,473.547332,0.207309,3.0,3,True,True,False,negative_prediction
6900,2025-04-20,2025-05-11,ILI,BE,3,50.1,-4.328267,autoARIMA,TFG,TFG::autoARIMA,...,54.428267,54.428267,2962.436200,0.518516,3.0,3,True,True,False,negative_prediction
6901,2025-04-20,2025-05-18,ILI,BE,4,55.7,-2.111930,autoARIMA,TFG,TFG::autoARIMA,...,57.811930,57.811930,3342.219272,0.550750,4.0,4,True,True,False,negative_prediction
6955,2025-07-27,2025-08-10,ILI,BE,2,54.3,-3.210640,autoARIMA,TFG,TFG::autoARIMA,...,57.510640,57.510640,3307.473758,0.547880,2.0,2,True,True,False,negative_prediction
6956,2025-07-27,2025-08-17,ILI,BE,3,45.6,-1.719388,autoARIMA,TFG,TFG::autoARIMA,...,47.319388,47.319388,2239.124495,0.450792,3.0,3,True,True,False,negative_prediction
6957,2025-07-27,2025-08-24,ILI,BE,4,67.4,-3.333349,autoARIMA,TFG,TFG::autoARIMA,...,70.733349,70.733349,5003.206595,0.673847,4.0,4,True,True,False,negative_prediction
7465,2024-03-10,2024-04-07,ILI,CZ,4,17.7,-1.442246,autoARIMA,TFG,TFG::autoARIMA,...,19.142246,19.142246,366.425583,0.931465,4.0,4,True,True,False,negative_prediction
7524,2024-06-23,2024-07-14,ILI,CZ,3,5.4,-0.621541,autoARIMA,TFG,TFG::autoARIMA,...,6.021541,6.021541,36.258962,0.293009,3.0,3,True,True,False,negative_prediction
7525,2024-06-23,2024-07-21,ILI,CZ,4,4.6,-0.966111,autoARIMA,TFG,TFG::autoARIMA,...,5.566111,5.566111,30.981590,0.270848,4.0,4,True,True,False,negative_prediction
7696,2025-04-20,2025-05-11,ILI,CZ,3,6.4,-2.097921,autoARIMA,TFG,TFG::autoARIMA,...,8.497921,8.497921,72.214666,0.413510,3.0,3,True,True,False,negative_prediction
7697,2025-04-20,2025-05-18,ILI,CZ,4,7.8,-1.989580,autoARIMA,TFG,TFG::autoARIMA,...,9.789580,9.789580,95.835882,0.476362,4.0,4,True,True,False,negative_prediction
10116,2024-01-07,2024-01-14,ILI,LT,1,45.2,-2.411654,"SARIMA(1,0,0)x(1,0,0)[52] (initial)",TFG,"TFG::SARIMA(1,0,0)x(1,0,0)[52] (initial)",...,47.611654,47.611654,2266.869594,2.326285,1.0,1,True,True,False,negative_prediction
10117,2024-01-07,2024-01-21,ILI,LT,2,93.4,-11.689676,"SARIMA(1,0,0)x(1,0,0)[52] (initial)",TFG,"TFG::SARIMA(1,0,0)x(1,0,0)[52] (initial)",...,105.089676,105.089676,11043.839915,5.134636,2.0,2,True,True,False,negative_prediction

ARI incidence file: latest-ARI_incidence.csv | shape: (6685, 4)
ILI incidence file: latest-ILI_incidence.csv | shape: (10646, 4)

Paired rows: 119741
Max truth difference after pairing: 0.0

Metric summary preview:

,scope,source,model,method,disease,h,mean_AE,median_AE,RMSE,mean_scaled_AE,...,reference_countries,reference_first_origin,reference_last_origin,reference_first_target,reference_last_target,coverage_vs_baseline,MAE_ratio_vs_baseline,scaled_AE_ratio_vs_baseline,rank_by_scaled_AE,rank_by_AE
0,common6,TFG,ensemble_mean_5,TFG::ensemble_mean_5,ARI,1,97.877169,54.893624,151.924379,0.469385,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.000000,0.723618,0.709044,1,1
1,common6,TFG,"SARIMA(1,0,0)x(1,0,0)[52] (initial)","TFG::SARIMA(1,0,0)x(1,0,0)[52] (initial)",ARI,1,99.999111,57.715043,154.483277,0.474127,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.000000,0.739306,0.716206,2,3
2,common6,TFG,ensemble_median_5,TFG::ensemble_median_5,ARI,1,99.567242,54.728252,153.139181,0.476651,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.000000,0.736113,0.720020,3,2
3,common6,TFG,autoARIMA,TFG::autoARIMA,ARI,1,102.941296,59.035537,156.738724,0.492070,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.000000,0.761058,0.743311,4,4
4,common6,TFG,DL_GlobalGRU_all_infections_all_countries,TFG::DL_GlobalGRU_all_infections_all_countries,ARI,1,104.407597,68.265372,157.119559,0.505035,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.000000,0.771899,0.762895,5,6
5,common6,RespiCast,safinea-PRFM,RespiCast::safinea-PRFM,ARI,1,103.502965,69.904746,151.061236,0.513165,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.444134,1.111991,1.133493,6,5
6,common6,TFG,rf_global_all_infections_all_countries,TFG::rf_global_all_infections_all_countries,ARI,1,110.059569,65.746841,169.915862,0.520027,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.000000,0.813684,0.785542,7,7
7,common6,TFG,RandomForest(lags=4),TFG::RandomForest(lags=4),ARI,1,122.120781,82.899359,179.640832,0.596299,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.000000,0.902855,0.900756,8,8
8,common6,RespiCast,ECDC-SARIMA,RespiCast::ECDC-SARIMA,ARI,1,131.683221,80.291968,195.093950,0.618137,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.810056,1.047707,1.072639,9,9
9,common6,RespiCast,ISI-FluBcast,RespiCast::ISI-FluBcast,ARI,1,133.142850,73.352095,217.925930,0.620742,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.648045,0.959302,0.946932,10,10
10,common6,RespiCast,fjordhest-ensemble,RespiCast::fjordhest-ensemble,ARI,1,159.259259,99.060000,219.539606,0.647889,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.301676,0.990769,0.987377,11,14
11,common6,RespiCast,respicast-quantileBaseline,RespiCast::respicast-quantileBaseline,ARI,1,135.260754,75.200000,210.139169,0.661997,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.000000,1.000000,1.000000,12,11
12,common6,RespiCast,respicast-hubEnsemble,RespiCast::respicast-hubEnsemble,ARI,1,138.080011,84.954405,214.839976,0.682167,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.997207,1.020074,1.030701,13,12
13,common6,RespiCast,ECDC-soca_simplex,RespiCast::ECDC-soca_simplex,ARI,1,140.517958,78.436681,220.605820,0.685738,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.946927,1.057590,1.064703,14,13
14,common6,RespiCast,ISI-FluABCaster,RespiCast::ISI-FluABCaster,ARI,1,182.201256,100.892678,282.366799,0.850669,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.405028,1.136214,1.148395,15,15
15,common6,RespiCast,MRC_GIDA-Prophet,RespiCast::MRC_GIDA-Prophet,ARI,1,208.895040,140.116617,284.764135,0.873046,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.106145,1.571790,1.991521,16,18
16,common6,RespiCast,MRC_GIDA-CATBoost,RespiCast::MRC_GIDA-CATBoost,ARI,1,184.836640,174.855665,194.551824,0.881606,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.013966,1.144216,1.568010,17,16
17,common6,RespiCast,NotreDame-Rt_cocirc,RespiCast::NotreDame-Rt_cocirc,ARI,1,191.724031,117.300000,293.889889,0.924108,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.720670,1.486409,1.467148,18,17
18,common6,RespiCast,ISI-SEIR_BRW,RespiCast::ISI-SEIR_BRW,ARI,1,226.755441,152.558745,319.182921,1.001251,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.198324,1.431715,1.480715,19,20
19,common6,RespiCast,ISI-LSTFlu,RespiCast::ISI-LSTFlu,ARI,1,215.122302,151.539577,310.948677,1.038469,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.329609,1.446567,1.473377,20,19
20,common6,RespiCast,ISI-GLEAM,RespiCast::ISI-GLEAM,ARI,1,251.690536,183.970000,341.300336,1.215168,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.312849,1.290086,1.388467,21,21
21,common6,RespiCast,MRC_GIDA-NHiTS,RespiCast::MRC_GIDA-NHiTS,ARI,1,347.338965,240.032014,502.423583,1.259818,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.106145,2.613484,2.873794,22,23
22,common6,RespiCast,MRC_GIDA-NBEATS,RespiCast::MRC_GIDA-NBEATS,ARI,1,363.171034,264.623997,499.158477,1.305265,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.106145,2.732610,2.977464,23,24
23,common6,RespiCast,MRC_GIDA-TiDE,RespiCast::MRC_GIDA-TiDE,ARI,1,384.303911,329.961665,534.253018,1.365025,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.092179,2.989212,3.253046,24,25
24,common6,RespiCast,safinea-syndromic,RespiCast::safinea-syndromic,ARI,1,336.171149,285.600000,433.751083,1.622084,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,0.175978,1.798210,1.867521,25,22
25,common6,TFG,DL_GlobalGRU_all_infections_all_countries,TFG::DL_GlobalGRU_all_infections_all_countries,ARI,2,128.154506,76.457574,192.294333,0.610183,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,1.000000,0.688033,0.669463,1,1
26,common6,TFG,ensemble_mean_5,TFG::ensemble_mean_5,ARI,2,128.740352,75.604710,196.539583,0.616819,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,1.000000,0.691179,0.676744,2,2
27,common6,TFG,ensemble_median_5,TFG::ensemble_median_5,ARI,2,130.168545,76.042097,199.933622,0.624327,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,1.000000,0.698846,0.684982,3,3
28,common6,TFG,"SARIMA(1,0,0)x(1,0,0)[52] (initial)","TFG::SARIMA(1,0,0)x(1,0,0)[52] (initial)",ARI,2,136.618023,83.157125,214.033052,0.639516,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,1.000000,0.733472,0.701647,4,4
29,common6,TFG,autoARIMA,TFG::autoARIMA,ARI,2,140.539903,74.496708,221.608875,0.656635,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,1.000000,0.754528,0.720429,5,6
30,common6,TFG,rf_global_all_infections_all_countries,TFG::rf_global_all_infections_all_countries,ARI,2,138.510157,89.040679,206.434364,0.672200,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,1.000000,0.743630,0.737506,6,5
31,common6,RespiCast,safinea-PRFM,RespiCast::safinea-PRFM,ARI,2,147.326206,98.741120,226.514546,0.719381,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.434659,1.031880,1.063457,7,7
32,common6,TFG,RandomForest(lags=4),TFG::RandomForest(lags=4),ARI,2,172.115675,111.432109,247.844622,0.843332,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,1.000000,0.924051,0.925263,8,8
33,common6,RespiCast,ECDC-SARIMA,RespiCast::ECDC-SARIMA,ARI,2,194.353799,125.700000,278.494677,0.871446,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.803977,1.023606,1.014185,9,13
34,common6,RespiCast,ISI-FluBcast,RespiCast::ISI-FluBcast,ARI,2,189.371419,105.617791,297.625760,0.882732,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.647727,1.015517,0.995427,10,11
35,common6,RespiCast,respicast-hubEnsemble,RespiCast::respicast-hubEnsemble,ARI,2,187.246986,110.680406,284.700021,0.904467,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.997159,1.004469,0.992495,11,10
36,common6,RespiCast,ECDC-soca_simplex,RespiCast::ECDC-soca_simplex,ARI,2,189.990708,112.091618,288.876717,0.909534,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.943182,1.012215,1.012827,12,12
37,common6,RespiCast,respicast-quantileBaseline,RespiCast::respicast-quantileBaseline,ARI,2,186.262074,124.375000,277.046960,0.911451,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,1.000000,1.000000,1.000000,13,9
38,common6,RespiCast,MRC_GIDA-Prophet,RespiCast::MRC_GIDA-Prophet,ARI,2,223.729070,156.737098,311.582361,0.941841,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.102273,1.035144,1.340378,14,15
39,common6,RespiCast,fjordhest-ensemble,RespiCast::fjordhest-ensemble,ARI,2,226.463704,168.940000,311.145173,0.956728,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.306818,0.974958,0.981236,15,16
40,common6,RespiCast,NotreDame-Rt_cocirc,RespiCast::NotreDame-Rt_cocirc,ARI,2,222.691051,139.200000,341.212369,1.061862,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.730114,1.231869,1.192324,16,14
41,common6,RespiCast,MRC_GIDA-NHiTS,RespiCast::MRC_GIDA-NHiTS,ARI,2,312.701081,235.102855,476.850572,1.092320,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.102273,1.446797,1.554532,17,20
42,common6,RespiCast,MRC_GIDA-TiDE,RespiCast::MRC_GIDA-TiDE,ARI,2,321.727011,191.880446,505.727589,1.096124,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.088068,1.479764,1.592267,18,21
43,common6,RespiCast,ISI-FluABCaster,RespiCast::ISI-FluABCaster,ARI,2,255.586261,151.907129,380.838256,1.156044,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.392045,1.092066,1.066027,19,18
44,common6,RespiCast,MRC_GIDA-NBEATS,RespiCast::MRC_GIDA-NBEATS,ARI,2,327.922971,195.363195,483.159322,1.167061,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.102273,1.517225,1.660899,20,22
45,common6,RespiCast,MRC_GIDA-CATBoost,RespiCast::MRC_GIDA-CATBoost,ARI,2,246.823989,263.364633,284.156555,1.318384,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.014205,1.185685,1.666516,21,17
46,common6,RespiCast,ISI-SEIR_BRW,RespiCast::ISI-SEIR_BRW,ARI,2,309.095908,220.986394,411.892860,1.415590,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.201705,1.476396,1.532743,22,19
47,common6,RespiCast,ISI-GLEAM,RespiCast::ISI-GLEAM,ARI,2,387.682243,325.590000,497.522407,1.849291,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.303977,1.591776,1.683616,23,23
48,common6,RespiCast,ISI-LSTFlu,RespiCast::ISI-LSTFlu,ARI,2,410.712154,305.300933,539.199699,1.925474,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.312500,1.722973,1.727627,24,24
49,common6,RespiCast,safinea-syndromic,RespiCast::safinea-syndromic,ARI,2,533.241042,443.013095,669.708460,2.471130,...,6,2024-10-13,2025-11-30,2024-10-27,2025-12-14,0.176136,2.311817,2.166020,25,25

MAIN TABLE:

,scope,disease,h,main_table_rank,source,model,mean_AE,mean_scaled_AE,RMSE,median_AE,...,coverage_vs_baseline,n_countries,mean_AE_ref_baseline,MAE_ratio_vs_baseline,scaled_AE_ratio_vs_baseline,n_negative_predictions,first_origin,last_origin,first_target,last_target
0,common6,ARI,1,1,TFG,ensemble_mean_5,97.877169,0.469385,151.924379,54.893624,...,1.000000,6,135.260754,0.723618,0.709044,0,2024-10-13,2025-12-07,2024-10-20,2025-12-14
1,common6,ARI,1,2,TFG,"SARIMA(1,0,0)x(1,0,0)[52] (initial)",99.999111,0.474127,154.483277,57.715043,...,1.000000,6,135.260754,0.739306,0.716206,0,2024-10-13,2025-12-07,2024-10-20,2025-12-14
2,common6,ARI,1,3,TFG,ensemble_median_5,99.567242,0.476651,153.139181,54.728252,...,1.000000,6,135.260754,0.736113,0.720020,0,2024-10-13,2025-12-07,2024-10-20,2025-12-14
3,common6,ARI,1,4,RespiCast,ECDC-SARIMA,131.683221,0.618137,195.093950,80.291968,...,0.810056,6,125.687069,1.047707,1.072639,0,2024-10-13,2025-12-07,2024-10-20,2025-12-14
4,common6,ARI,1,5,RespiCast,ISI-FluBcast,133.142850,0.620742,217.925930,73.352095,...,0.648045,6,138.791379,0.959302,0.946932,0,2024-10-13,2025-12-07,2024-10-20,2025-12-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,global,ILI,4,2,TFG,ensemble_mean_5,50.456452,1.274930,109.191286,12.154271,...,1.000000,10,70.959091,0.711064,0.715817,0,2024-10-13,2025-11-16,2024-11-10,2025-12-14
92,global,ILI,4,3,TFG,ensemble_median_5,53.069211,1.337350,114.005698,12.638120,...,1.000000,10,70.959091,0.747885,0.750863,0,2024-10-13,2025-11-16,2024-11-10,2025-12-14
93,global,ILI,4,4,RespiCast,ItaLuxColab-EpiNetEKF,57.947189,1.437155,116.248995,15.727635,...,0.888112,10,75.932382,0.763142,0.744317,0,2024-10-13,2025-11-16,2024-11-10,2025-12-14
94,global,ILI,4,5,RespiCast,respicast-hubEnsemble,61.283887,1.486261,127.972350,16.445343,...,1.000000,10,70.959091,0.863651,0.834470,0,2024-10-13,2025-11-16,2024-11-10,2025-12-14
95,global,ILI,4,6,RespiCast,respicast-quantileBaseline,70.959091,1.781084,146.226370,20.800000,...,1.000000,10,70.959091,1.000000,1.000000,0,2024-10-13,2025-11-16,2024-11-10,2025-12-14

Saved final clean RespiCast comparison outputs to:
C:\Users\aolas\UNI PYTHON\TFG\results\final_test_2024_2025\respicast_final_clean_tables

Generated files:
- 00_column_dictionary.csv
- 01_horizon_date_audit.csv
- 02_prediction_quality_audit.csv
- 03_invalid_or_extreme_prediction_rows.csv
- 04_duplicate_prediction_key_audit.csv
- 05_scales_used.csv
- 06_paired_forecasts_vs_baseline.csv
- 07_zero_error_audit.csv
- 08_metric_summary_all_methods.csv
- 09_MAIN_top3_TFG_vs_top2_RespiCast_plus_baseline.csv
- 10_top10_all_methods_by_scope_disease_horizon.csv
- 11_top10_coverage_filtered.csv
- 12_tfg_positions_only.csv
- 13_respicast_positions_only.csv
- 14_reference_universe.csv
- 00_methodology_notes.txt

============================================================
MAIN FINAL TABLE
============================================================

,scope,disease,h,main_table_rank,source,model,mean_AE,mean_scaled_AE,RMSE,median_AE,...,coverage_vs_baseline,n_countries,mean_AE_ref_baseline,MAE_ratio_vs_baseline,scaled_AE_ratio_vs_baseline,n_negative_predictions,first_origin,last_origin,first_target,last_target
0,common6,ARI,1,1,TFG,ensemble_mean_5,97.877169,0.469385,151.924379,54.893624,...,1.000000,6,135.260754,0.723618,0.709044,0,2024-10-13,2025-12-07,2024-10-20,2025-12-14
1,common6,ARI,1,2,TFG,"SARIMA(1,0,0)x(1,0,0)[52] (initial)",99.999111,0.474127,154.483277,57.715043,...,1.000000,6,135.260754,0.739306,0.716206,0,2024-10-13,2025-12-07,2024-10-20,2025-12-14
2,common6,ARI,1,3,TFG,ensemble_median_5,99.567242,0.476651,153.139181,54.728252,...,1.000000,6,135.260754,0.736113,0.720020,0,2024-10-13,2025-12-07,2024-10-20,2025-12-14
3,common6,ARI,1,4,RespiCast,ECDC-SARIMA,131.683221,0.618137,195.093950,80.291968,...,0.810056,6,125.687069,1.047707,1.072639,0,2024-10-13,2025-12-07,2024-10-20,2025-12-14
4,common6,ARI,1,5,RespiCast,ISI-FluBcast,133.142850,0.620742,217.925930,73.352095,...,0.648045,6,138.791379,0.959302,0.946932,0,2024-10-13,2025-12-07,2024-10-20,2025-12-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,global,ILI,4,2,TFG,ensemble_mean_5,50.456452,1.274930,109.191286,12.154271,...,1.000000,10,70.959091,0.711064,0.715817,0,2024-10-13,2025-11-16,2024-11-10,2025-12-14
92,global,ILI,4,3,TFG,ensemble_median_5,53.069211,1.337350,114.005698,12.638120,...,1.000000,10,70.959091,0.747885,0.750863,0,2024-10-13,2025-11-16,2024-11-10,2025-12-14
93,global,ILI,4,4,RespiCast,ItaLuxColab-EpiNetEKF,57.947189,1.437155,116.248995,15.727635,...,0.888112,10,75.932382,0.763142,0.744317,0,2024-10-13,2025-11-16,2024-11-10,2025-12-14
94,global,ILI,4,5,RespiCast,respicast-hubEnsemble,61.283887,1.486261,127.972350,16.445343,...,1.000000,10,70.959091,0.863651,0.834470,0,2024-10-13,2025-11-16,2024-11-10,2025-12-14
95,global,ILI,4,6,RespiCast,respicast-quantileBaseline,70.959091,1.781084,146.226370,20.800000,...,1.000000,10,70.959091,1.000000,1.000000,0,2024-10-13,2025-11-16,2024-11-10,2025-12-14

============================================================
TFG POSITIONS
============================================================

,scope,source,model,method,disease,h,mean_AE,median_AE,RMSE,mean_scaled_AE,...,reference_countries,reference_first_origin,reference_last_origin,reference_first_target,reference_last_target,coverage_vs_baseline,MAE_ratio_vs_baseline,scaled_AE_ratio_vs_baseline,rank_by_scaled_AE,rank_by_AE
0,common6,TFG,ensemble_mean_5,TFG::ensemble_mean_5,ARI,1,97.877169,54.893624,151.924379,0.469385,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.0,0.723618,0.709044,1,1
1,common6,TFG,"SARIMA(1,0,0)x(1,0,0)[52] (initial)","TFG::SARIMA(1,0,0)x(1,0,0)[52] (initial)",ARI,1,99.999111,57.715043,154.483277,0.474127,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.0,0.739306,0.716206,2,3
2,common6,TFG,ensemble_median_5,TFG::ensemble_median_5,ARI,1,99.567242,54.728252,153.139181,0.476651,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.0,0.736113,0.720020,3,2
3,common6,TFG,autoARIMA,TFG::autoARIMA,ARI,1,102.941296,59.035537,156.738724,0.492070,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.0,0.761058,0.743311,4,4
4,common6,TFG,DL_GlobalGRU_all_infections_all_countries,TFG::DL_GlobalGRU_all_infections_all_countries,ARI,1,104.407597,68.265372,157.119559,0.505035,...,6,2024-10-13,2025-12-07,2024-10-20,2025-12-14,1.0,0.771899,0.762895,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,global,TFG,ensemble_median_5,TFG::ensemble_median_5,ILI,4,53.069211,12.638120,114.005698,1.337350,...,10,2024-10-13,2025-11-16,2024-11-10,2025-12-14,1.0,0.747885,0.750863,5,6
108,global,TFG,DL_GlobalGRU_all_infections_all_countries,TFG::DL_GlobalGRU_all_infections_all_countries,ILI,4,50.997418,10.589691,109.381157,1.361551,...,10,2024-10-13,2025-11-16,2024-11-10,2025-12-14,1.0,0.718688,0.764450,6,4
109,global,TFG,"SARIMA(1,0,0)x(1,0,0)[52] (initial)","TFG::SARIMA(1,0,0)x(1,0,0)[52] (initial)",ILI,4,59.833497,17.310576,126.407011,1.493132,...,10,2024-10-13,2025-11-16,2024-11-10,2025-12-14,1.0,0.843211,0.838327,10,9
110,global,TFG,RandomForest(lags=4),TFG::RandomForest(lags=4),ILI,4,68.894534,17.465018,142.177891,1.638556,...,10,2024-10-13,2025-11-16,2024-11-10,2025-12-14,1.0,0.970905,0.919976,13,15
111,global,TFG,autoARIMA,TFG::autoARIMA,ILI,4,61.780247,16.434559,132.315986,1.656836,...,10,2024-10-13,2025-11-16,2024-11-10,2025-12-14,1.0,0.870646,0.930240,14,11

============================================================
ZERO ERROR AUDIT
============================================================

,scope,source,model,method,disease,h,n_pairs,n_y_zero,n_pred_model_zero,n_pred_ref_zero,n_model_AE_zero,n_ref_AE_zero,n_both_AE_zero,mean_AE_model,mean_AE_ref
0,common6,RespiCast,ECDC-SARIMA,RespiCast::ECDC-SARIMA,ARI,1,290,1,0,0,0,0,0,131.683221,125.687069
8,common6,RespiCast,ECDC-soca_simplex,RespiCast::ECDC-soca_simplex,ARI,1,339,1,0,0,0,0,0,140.517958,132.866224
16,common6,RespiCast,ISI-FluABCaster,RespiCast::ISI-FluABCaster,ARI,1,145,1,0,0,0,0,0,182.201256,160.358276
24,common6,RespiCast,ISI-FluBcast,RespiCast::ISI-FluBcast,ARI,1,232,1,0,0,0,0,0,133.142850,138.791379
32,common6,RespiCast,ISI-GLEAM,RespiCast::ISI-GLEAM,ARI,1,112,1,0,0,0,0,0,251.690536,195.095982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,global,TFG,"SARIMA(1,0,0)x(1,0,0)[52] (initial)","TFG::SARIMA(1,0,0)x(1,0,0)[52] (initial)",ILI,4,572,23,0,13,0,12,0,59.833497,70.959091
431,global,TFG,autoARIMA,TFG::autoARIMA,ILI,4,572,23,19,13,12,12,7,61.780247,70.959091
439,global,TFG,ensemble_mean_5,TFG::ensemble_mean_5,ILI,4,572,23,0,13,0,12,0,50.456452,70.959091
447,global,TFG,ensemble_median_5,TFG::ensemble_median_5,ILI,4,572,23,0,13,0,12,0,53.069211,70.959091
455,global,TFG,rf_global_all_infections_all_countries,TFG::rf_global_all_infections_all_countries,ILI,4,572,23,0,13,0,12,0,51.256532,70.959091

============================================================
PREDICTION QUALITY AUDIT
============================================================

,source,model,method,disease,h,pred_quality_flag,n_rows,min_pred,max_pred,mean_pred,first_origin,last_origin,first_target,last_target
112,RespiCast,NotreDame-Rt_cocirc,RespiCast::NotreDame-Rt_cocirc,ILI,1,above_100000_per_100000,1,2.842952e+08,2.842952e+08,2.842952e+08,2025-06-15,2025-06-15,2025-06-22,2025-06-22
114,RespiCast,NotreDame-Rt_cocirc,RespiCast::NotreDame-Rt_cocirc,ILI,2,above_100000_per_100000,1,5.725977e+15,5.725977e+15,5.725977e+15,2025-06-15,2025-06-15,2025-06-29,2025-06-29
116,RespiCast,NotreDame-Rt_cocirc,RespiCast::NotreDame-Rt_cocirc,ILI,3,above_100000_per_100000,1,1.153267e+23,1.153267e+23,1.153267e+23,2025-06-15,2025-06-15,2025-07-06,2025-07-06
118,RespiCast,NotreDame-Rt_cocirc,RespiCast::NotreDame-Rt_cocirc,ILI,4,above_100000_per_100000,1,2.322790e+30,2.322790e+30,2.322790e+30,2025-06-15,2025-06-15,2025-07-13,2025-07-13
0,RespiCast,ECDC-SARIMA,RespiCast::ECDC-SARIMA,ARI,1,finite_non_negative_plausible,407,9.150812e+00,2.828806e+03,8.908229e+02,2024-10-13,2025-12-07,2024-10-20,2025-12-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,TFG,autoARIMA,TFG::autoARIMA,ILI,2,negative_prediction,33,-1.580170e+01,-2.948716e-98,-2.809473e+00,2024-03-10,2025-11-09,2024-03-24,2025-11-23
219,TFG,autoARIMA,TFG::autoARIMA,ILI,3,negative_prediction,46,-2.740079e+01,-2.603163e-98,-3.916548e+00,2024-03-10,2025-11-09,2024-03-31,2025-11-30
221,TFG,autoARIMA,TFG::autoARIMA,ILI,4,negative_prediction,56,-2.709863e+01,-1.961124e-98,-4.294071e+00,2024-01-07,2025-11-09,2024-02-04,2025-12-07
227,TFG,ensemble_mean_5,TFG::ensemble_mean_5,ILI,1,negative_prediction,1,-2.853516e-01,-2.853516e-01,-2.853516e-01,2025-05-11,2025-05-11,2025-05-18,2025-05-18
229,TFG,ensemble_mean_5,TFG::ensemble_mean_5,ILI,2,negative_prediction,1,-1.957035e-01,-1.957035e-01,-1.957035e-01,2025-05-11,2025-05-11,2025-05-25,2025-05-25

============================================================
SCALES USED
============================================================

   disease location  mase_scale
0      ARI       BE  299.077262
1      ARI       BG  184.456148
2      ARI       CZ  192.408585
3      ARI       DE  325.907657
4      ARI       EE   79.899768
5      ARI       LT  160.480639
6      ARI       RO  138.173318
7      ARI       SI  430.407657
8      ILI       BE  112.301160
9      ILI       CZ   20.550696
10     ILI       EE   42.106381
11     ILI       GR  177.528066
12     ILI       IE   12.476450
13     ILI       LT   20.466821
14     ILI       NL   17.484919
15     ILI       PL   94.136079
16     ILI       RO    2.649768
17     ILI       SI   13.849188